django_ORM/mysite/articles/urls.py
from django.urls import path
# views.py가 urls.py와 동일한 위치에 있음
from . import views

app_name = "articles"

urlpatterns = [
    # 이름 - 1. 또 다른 app을 생성했을 때 어디로 가야할지 참조하기 위해 지음
    #       2. 수정시 모든 페이지의 경로를 수정하지 않아도 되도록
    path('', views.index, name="index"), # articles/로만 접속할 수 있다.
    path('new/', views.new, name="new"),
    path('create/', views.create, name="create"),
    path('introduce/', views.introduce, name="introduce"),
    # variable routing: view함수에서 사용
    path('<int:article_pk>/', views.detail, name="detail"),
    path('<int:article_pk>/delete', views.delete, name="delete"),
    path('<int:article_pk>/edit', views.edit, name="edit"),
    path('<int:article_pk>/update', views.update, name="update"),
]

django_ORM/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include # include 모듈 포함

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
]

django_ORM/mysite/articles/models.py
from django.db import models

# Create your models here.

# 파이썬 convention - 단수형태. 맨 앞글자 대문자!!
# 장고가 미리 만들어 놓은 객체를 상속받는다.
class Article(models.Model): 
    # DB에 생성되는 테이블 이름: articles_article (app이름_클래스이름)
    title = models.CharField(max_length=150) # CharField는 max_length를 반드시 넣어줘야 함
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True) # DB에 생성한 시간
    updated_at = models.DateTimeField(auto_now=True) # 수정되는 시간 저장
    #boolean = models.BooleanField(blank=True) # blank=True: 비어있어도 상관없다
    
    # 매직 메소드(객체를 예쁘게 출력해주는 특수 메소드)
    #   => migrate는 할 필요 없지만 shell은 다시 켜야 한다.
    def __str__(self): # 인스턴스 메소드
        return f'{self.id}번째글 - {self.title} : {self.content}'
    

django_ORM/mysite/articles/views.py
from django.shortcuts import render, redirect
#모델 가져오기
from .models import Article

# Create your views here.
def index(request):
    # [ORM 사용 가능]
    # 전체 데이터 가져오기
    articles = Article.objects.all()[::-1]
    # 그 데이터 템플릿에게 넘겨주기
    context = {
        'articles' : articles
    }
    # 템플릿에서 반복문으로 각각의 게시글의 pk, title 보여주기 


    # 파일이름X. 경로!
    # articles_index.html로 해도 되지만 이름이 너무 길어지므로 
    # templates 폴더 안에 app 이름으로 폴더 하나 더 만든다.
    return render(request, 'articles/index.html', context)

def new(request):
    return render(request, 'articles/new.html')

def create(request):
    # request.GET은 query_dict 타입이므로 키값으로 값을 가져올 수 있다.(get메소드)
    title = request.POST.get('title')
    content = request.POST.get('content')
    
    # 데이터 생성을 위한 ORM 활용
    # 첫번째 방법
    # article = Article()
    # article.title = title
    # article.content = content
    # article.save()

    # 두번째 방법
    # article = Article(title=title, content=content)
    # article.save()

    # 세번째 방법
    Article.objects.create(title=title, content=content)
    # save() 메소드 사용 안해도 됨
    
    # 단순히 이렇게 하면 폼태그의 create/ 주소로 가므로 빈 html이 나오게 된다.
    #return render(request, 'articles/index.html')
    return redirect('articles:index') # app_name:경로이름

# 1. /introduce/ 경로
# 2. h1 태그로 이루어진 제목
# 2-1. 각각의 p태그에 이름과 나이 작성
# 3. back 링크로 index로 돌아갈 수 있는 링크 하나
# 4. index에서 introduce로 이동할 수 있는 링크 하나
# 5. base.html 상속받아서 block body 안에 작성
def introduce(request):
    return render(request, 'articles/introduce.html')

# 1. 상세페이지를 보기위한 경로
# 1-1. 특정 게시글에 대한 고유 값
# 1-2. /articles/1/, /articles/2/
#   /articles/{{ article.pk }}/
# 2. {% url 'articles:detail' article.pk %}
# 2-1. 게시글의 pk, title, ...
# 3. 인덱스 페이지로 돌아가는 링크
def detail(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    context ={
        'article':article,
    }
    return render(request, 'articles/detail.html', context)

# 1. 특정 글 삭제를 위한 경로 생성
# 2. 글 삭제 처리를 해주는 view 작성
# 3. 글 삭제 후, index page로 redirect
# 4. 글 삭제를 위한 링크 detail에 작성
def delete(request, article_pk):
    # request.method
    article = Article.objects.get(pk=article_pk)
    article.delete()
    return redirect('articles:index')

# edit
# 1. 특정 글 수정을 위한 경로 생성
# 1-1. /articles/1/edit/
# 2. 글 수정 template을 render하는 edit view 작성
# 2-1. 해당 template에 form tag 작성
# 2-2. 각 input tag 내부에 기존 내용이 들어있어야 함
# 2-3. value 속성을 활용한다.
def edit(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    context = {
        'article' : article
    }
    return render(request, 'articles/edit.html', context)

# update
# 3. edit에서 보낸 데이터 처리를 위한 경로 생성
# 3-1. /articles/1/update/
# 4. 글 수정 처리를 하는 update view 작성
# 5. 해당 글 상세 페이지로 redirect
# 5-1. redirect('app_name:path_name', article.pk)
# 6. 글 수정을 위한 edit 링크 상세 페이지에 생성
# 6-1. {% url 'articles:edit' article.pk %}
def update(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    article.title = request.POST.get('title')
    article.content = request.POST.get('content')
    article.save()
    return redirect('articles:detail', article.pk)

    

django_ORM/mysite/articles/templates/articles/create.html
{% extends 'base.html' %}
{% block body %}
<h1>글 작성 완료</h1>
<hr>
<h2>제목은 {{ title }} </h2>
<p>본문은 {{ content }}</p>
<hr>
<!-- 항상 주소 말고 이름으로 접근하는 것이 좋다. -->
<a href="{% url 'articles:index' %}">back</a>
{% endblock %}

django_ORM/mysite/articles/templates/articles/detail.html
{% extends 'base.html' %}
{% block body %}
  <h1>상세 페이지</h1>
  <hr>
  <h3>{{ article.pk }}번째 글</h3>
  <p>제목 : {{ article.title }}</p>
  <p>내용 : {{ article.content }}</p>
  <p>생성 시간 : {{ article.created_at }}</p>
  <p>수정 시간 : {{ article.updated_at }}</p>
  <a href="{% url 'articles:index' %}">[back]</a>
  <a href="{% url 'articles:edit' article.pk %}">[수정]</a>
  <a href="{% url 'articles:delete' article.pk %}">[삭제]</a>
{% endblock %}

django_ORM/mysite/articles/templates/articles/edit.html
{% extends 'base.html' %}
{% block body %}
  <h1>글 수정</h1>
  <hr>
  <!-- url명령어 '경로' view함수의 매개변수 -->
  <form action="{% url 'articles:update' article.pk %}" method="POST"> 
    <!-- 크롬 개발자 모드에서 보면
      GET> Query String: 내용 그대로 노출 => POST> form data: 해시값으로 변경됨 -->
    <!-- <input type="hidden" name="csrfmiddlewaretoken" value="9D84qDV78qhhwUONlbHtan0IvyWACuWpsENkHpP0YU8hiVy9boDo6S71uuBQQJh1"> -->
    {% csrf_token %} 
    <!-- 이런 형식으로 작성하면 '제목'이 그냥 text가 아니라 input태그의 라벨이 된다.
        => '제목'을 클릭했을 때 포커싱이 input태그로 맞춰진다. -->
    <label for="name">제목 : </label>
    <input type="text" id="name" name="title" value="{{ article.title }}">

    <label for="cnt">내용 : </label>
    <input type="text" id="cnt" name="content" value="{{ article.content }}">

    <input type="submit" value="수정">
  </form>

{% endblock %}

django_ORM/mysite/articles/templates/articles/index.html
{% extends 'base.html' %}
{% block body %}
  <h1>게시판</h1>
  <hr>
  {% for article in articles %}
    <h3>{{ article.pk }}번 째 글</h3>
    <h4>제목 : {{ article.title }}</h4>
    <a href="{% url 'articles:detail' article.pk %}">[DETAIL]</a>
    <!-- <a href="/articles/{{ article.pk }}/"></a> -->
    <hr>
  {% endfor %}
  <a href="{% url 'articles:new' %}">NEW</a>
  <hr>

  <h1>자기소개</h1>
  <hr>
  <!-- 변수 불러오는 것과 같음 -->
  <a href="{% url 'articles:introduce' %}">GO</a>
  <hr>
{% endblock %}

django_ORM/mysite/articles/templates/articles/introduce.html
{% extends 'base.html' %}
{% block body %}
<h1>자기소개</h1>
<hr>
<p>내 이름은 김현정</p>
<p>내 나이는 안알랴줌</p>
<hr>
<a href="{% url 'articles:index' %}">back</a>

{% endblock %}

django_ORM/mysite/articles/templates/articles/new.html
{% extends 'base.html' %}
{% block body %}
<h1>글 작성 페이지</h1>
<hr>
  <!-- <form action="/articles/create/"> -->
  <form action="{% url 'articles:create' %}" method="GET">  
    <!-- 이런 형식으로 작성하면 '제목'이 그냥 text가 아니라 input태그의 라벨이 된다.
        => '제목'을 클릭했을 때 포커싱이 input태그 전체로 맞춰진다. -->
    <label for="name">제목 : </label>
    <input type="text" id="name" name="title">

    <label for="cnt">내용 : </label>
    <input type="text" id="cnt" name="content">

    <input type="submit" value="글 작성">
  </form>
{% endblock %}

django_ORM/mysite/mysite/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <!-- 이 구간을 한 블록으로 잡겠다(title, body 등은 내가 지정한 이름) -->
  <title>
    {% block title %}
      Document
    {% endblock %}
  </title>
</head>
<body>
  <!-- 부트스트랩은 항상 container division으로 만든다 -->
  <div class="container">
    {% block body %}
    {% endblock %}
  </div>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>